; This file was automatically generated by ScriptHubImporter.py
<<<<<<< Updated upstream
global g_ImportsGameVersion64 := 647
global g_ImportsGameVersionPostFix64 := ".2"
=======
global g_ImportsGameVersion64 := 635
global g_ImportsGameVersionPostFix64 := ""
>>>>>>> Stashed changes
global g_ImportsGameVersionPlatform64 := "Steam"