; Automatically generated by Addon Management
#include *i %A_LineFile%\..\IC_Core\IC_Core_Includes.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_LevelUp_Extra\IC_BrivGemFarm_LevelUp_Component.ahk
#include *i %A_LineFile%\..\IC_About\IC_About_Component.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_AdvancedSettings\IC_BrivGemFarm_AdvancedSettings_Includes.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_Performance\IC_BrivGemFarm_Component.ahk
#include *i %A_LineFile%\..\IC_ChestPurchaser\IC_ChestPurchaser_Component.ahk
#include *i %A_LineFile%\..\IC_RNGWaitingRoom_Extra\IC_RNGWaitingRoom_Includes.ahk
